### PR TITLE
Enhance plugin's reporting functionality

### PR DESCRIPTION
**Pull request by progala**
This PR adds reporting functionality similar to the one implemented in the Golden Configuration Plugin.

Initially we're implementing two models for recording per-device and per-inventory item validation results. These tables are populated by the corresponding jobs and need to be run manually.

Two reports are provided here, one for the Devices Validated Software and one for Inventory Validated Software.

- Devices Validated Software provides bar chart showing Device Platform breakdown and Table with Device Type breakdown. Report can be filtered on Devices, Device types, Device roles, Software.

- Inventory Item Validated Software provides bar chart showing Inventory Item Manufacturer breakdown and Table with Device Type Name. Report can be filtered on Inventory Items, Devices, Device types, Device roles, Software.

Device Software Validation Reports - Nautobot

Inventory Item Software Validation Reports - Nautobot

### CODE REVIEW

**Review by dgarros — COMMENTED** [review]
Looks good to me, great work @progala @pszulczewski

**Comment by progala** [comment]
@dgarros @jvanderaa @josh5276 @pszulczewski 

This PR is now ready for the full review.

**Review by pszulczewski — APPROVED** [review]
Great work @progala!
I like the way how you generalized the part where we create charts with `bar_chart_attrs` and `pie_chart_attrs `.

**Comment by jvanderaa** [comment]
Once the conflicts are covered, good to merge.

**Comment by josh5276** [comment]
Yes, this is great work guys! Can't wait to take some of this framework and retrofit it into the hardware portions. :)

**Review by josh5276 — APPROVED** [review]

**Comment by pszulczewski** [comment]
I am not sure why pylint terminates with an exception?
I merged with develop branch to resolve conflicts in pyproject.toml and updated poetry.lock file.
Can someone more experienced have a look and advise?

**Comment by pszulczewski** [comment]
Sorry I am not able to find the issue my self.
When I merge with develop when the main container starts it exits with this Exception:
```
nautobot_1  | Traceback (most recent call last):
nautobot_1  |   File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 236, in create
nautobot_1  |     app_name = app_config_class.name
nautobot_1  | AttributeError: type object 'NautobotConfig' has no attribute 'name'
```
I am bringing back the branch to the last working commit.

**Comment by dgarros** [comment]
@pszulczewski I've updated the lock file and now the tests are passing

**Comment by pszulczewski** [comment]
Thanks @dgarros, it looks like it was failing with nautobot core 1.1.3 and you changed it to 1.1.6 in CI.
I changed nautobot version from 1.1.3 to 1.1.6 in `tasks.py` locally and now build is fine. I think it may be worth updating `tasks.py` to 1.1.6 here.

**Pull request merged**
