### PR TITLE
Add `alias` field to Validated Software List CSV Export

### PR DESCRIPTION
**Pull request by MeganerdDev**
# Closes: [#152](https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/issues/152)

# What's Changed
This adds the `alias` header and data for the CSV export file  `nautobot_Validated Softwares.csv` from the `/plugins/nautobot-device-lifecycle-mgmt/validated-software/` page

Previous columns for Validated Software List export:
software,devices,device_types,device_roles,inventory_items,object_tags,start,end,preferred

Proposed columns for Validated Software List export:
software,devices,device_types,device_roles,inventory_items,object_tags,start,end,preferred,alias

# TODO
- [x] `$ nautobot-server makemigrations` creates `alias` column in `nautobot_device_lifecycle_mgmt_validatedsoftwarelcm` PostgreSQL database table
- [x] CSV export file contains added `alias` as header
- [x] CSV export file contains `alias` data for each column item
- [ ] Discuss re-ordering the alias column so that isn't that last column item

### CODE REVIEW

**Comment by MeganerdDev** [comment]
@progala does this look good for merge?

Or did you want me to PR the change to add object tags for the software list from this patch?
https://github.com/MeganerdDev/nautobot-plugin-device-lifecycle-mgmt/tree/nikko-csv-export-patch-2

**Comment by jvanderaa** [comment]
@progala can you help out @MeganerdDev here?

**Comment by progala** [comment]
@MeganerdDev Apologies, this fell off my radar. I sent you an invite and we can review this together.

**Comment by progala** [comment]
Can you tell me if what you're after is a new `alias` field on the ValidatedSoftware that is independent from Software `alias` field or you just want to have Software `alias` field included in the ValidatedSoftware csv export?

If it's the former, we'd have to ensure forms, api views, etc., are all updated as well.

If it's the latter then I suggest using custom export templates instead of modifying the default export. E.g.

```
software,software_alias,start,end,preferred
{% for vs in queryset -%}
{{vs.software.version}},{{vs.software.alias}},{{vs.start}},{{vs.end}},{{vs.preferred}},
{% endfor %}
```

**Comment by MeganerdDev** [comment]
Closing wit Progala's solution

**Pull request closed without merging**
