### PR TITLE
Fix DjangoObjectType Import

### PR DESCRIPTION
**Pull request by jdrew82**
The DjangoObjectType class was being imported from Nautobot and should have been imported from `graphene_django`. This is causing Nautobot 1.2.0-beta.1 to crash when the Lifecycle plugin is enabled. Fixing the import corrects the crashing.

### CODE REVIEW

**Comment by dgarros** [comment]
@progala has a PR already opened to fix that, .. and other things
https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/pull/37/files

Maybe we can merge this one quickly to unblock the testing of this plugin with 1.2
@jvanderaa @josh5276 what do you guys think ?

**Comment by josh5276** [comment]
Yea, that works for me. We can get @progala PR merged so that we blocking 1.2 testing, then circle back to the dummy import idea.

**Comment by progala** [comment]
@dgarros @jvanderaa 

I've updated my PR and tested is successfully with 1.1.3 and 1.2.0b1. We could merge it now if you're happy with it.

https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/pull/37

**Comment by dgarros** [comment]
Closing this one since we merged #37

**Pull request closed without merging**
