### PR TITLE
Add validated software to device types

### PR DESCRIPTION
**Pull request by zackt25**
### Closes: #42 - Display matching Validated Softwares to Device Types.
___
### Scenario  1: Device type has only 1 validated software assigned

image

image
___
### Scenario  2: Device type has 2 validated software assigned

image

image

image
___
### Scenario  3: Device type has 2 validated softwares assigned and Device software is not valid

image

image

image

### CODE REVIEW

**Comment by joewesch** [comment]
LGTM, great job @zackt25.

**Review by progala — CHANGES_REQUESTED** [review]
@zackt25 Thanks for working on this feature. I've reviewed the code and made suggestions. Let me know if you'd like to chat about these.

**Comment by zackt25** [comment]
How can I get the tests to pass is there something needed in the Pipeline?

**Comment by itdependsnetworks** [comment]
Seems like a packaging/poetry issue, this is the error you are getting 
```
    from zipp import Path as ZipPath  # type: ignore
ModuleNotFoundError: No module named 'zipp'
```

**Pull request closed without merging**
